# !! Environment variables are currently not applied, if there are any plans of implementation within Docker, talk to Finn.
# This Docker Environment is set up WITHOUT persistent storage, if you want persistent storage, then Finn has an image for this available.
  # For now it will just re-create the DB based on the scripts within database-scripts via entrypoint.sh
# This build is not tuned correctly, please make sure not to put this image under too much load to avoid system instability!

# ! THIS DOCKER ENVIRONMENT IS ONLY MEANT FOR DEVELOPMENT, NOT PRODUCTION!!!

# I'm assuming the Web-Client that handles PHP Locally does not run via a docker script, in which case, it *should* work without issue.

# If you encounter any issues running the services, make sure all shell scripts have LF line endings and not CLRF!!
services:
  # Database
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    container_name: MSSQL-Database
    ports:
      - "1434:1433"  # Expose port 1434 on the host, map to 1433 in the container
    env_file:
      - dev.env 
    volumes:
      - ./database/database-scripts:/var/opt/mssql/scripts
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge