# ! THIS DOCKER ENVIRONMENT IS ONLY MEANT FOR DEVELOPMENT, NOT PRODUCTION !

# Currently this Docker Environment does NOT use a persistent data volume for the Database
# This build is not tuned correctly per resources, please make sure not to put this image under too much load to avoid system instability

# If you encounter any issues running the services, make sure all shell scripts have LF line endings and not CLRF!!
# Docker Env set up by Finn, if there are any problems, please contact me.

services:
  # Database
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    container_name: MSSQL-Database
    ports:
      - "1434:1433"  # Expose port 1434 on the host, map to 1433 in the container
    env_file:
      - dev.env 
    volumes:
      - ./database/database-scripts:/var/opt/mssql/scripts
    networks:
      - sql_network
  # PHP Webserver
  webserver:
    platform: "linux/amd64"
    build:
      context: ./webserver-setup
      dockerfile: Dockerfile.dev
    container_name: PHP-Webserver
    env_file:
      - dev.env
    depends_on:
      - database
    ports:
      - "8080:80"  # Expose port 8080 on the host, map to 80 in the container
    volumes:
      - ./application/:/application/  # App code
      - ./webserver-setup/:/setup/
    entrypoint: ["php", "-S", "0.0.0.0:80", "-t", "/application/"]  # Start PHP Webserver 
    networks:
      - sql_network


networks:
  sql_network:
    driver: bridge