# Use the official Microsoft SQL Server image
FROM mcr.microsoft.com/mssql/server:2022-latest

# Create a new directory for sql scripts
RUN mkdir -p /var/opt/mssql/scripts

# Copy the entrypoint script that will run the SQL script after SQL Server starts
COPY entrypoint.sh /usr/local/bin/

# Expose SQL Server port 1433 inside the container (For Backend Usage)
EXPOSE 1433

# Set the entrypoint to run our shell script.
ENTRYPOINT ["/bin/bash", "/usr/local/bin/entrypoint.sh"]